# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CoThings
email: info@cothings.app
description: > # this means to ignore newlines until "baseurl:"
  CoThings is application to account for current number of people using shared areas or utilities in realtime. 
  The project’s main purpose is avoiding you to visit crowded areas during COVID-19 pandemic if you live in a community.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cothings.app" # the base hostname & protocol for your site
twitter_username: cothings
github_username:  rainlab-inc/cothings
# gitlab_username:  

# Outputting
permalink: /:categories/:year/:month/:day/:title

# Build settings
markdown: kramdown
exclude: ["README.md", "Dockerfile", "jekyll", "Gemfile", "Gemfile.lock"]